apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: multi-k8s-timheng-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: timheng.com
  dnsNames:
    - timheng.com
    - www.timheng.com
